prompts:
  - |
    Generate a curl command that fetches ONLY the top 9 most-starred repositories from the "microsoft" organization using a placeholder 
    API key ($API_KEY).
    The command must:
      - Use the GitHub API endpoint for organization repositories
      - Be in this exact format: 
        curl -H "Authorization: Bearer $API_KEY" "https://api.github.com/orgs/microsoft/repos?per_page=9&sort=stars&direction=desc"
      - Use the correct header with placeholder $API_KEY
      - Ensure it is syntactically valid and ready to copy-paste into a shell

providers:
  - openrouter:openai/gpt-4o-mini with max_tokens: 1024
  - openrouter:openai/gpt-4.1-nano with max_tokens: 1024
  - openrouter:google/gemini-2.0-flash-lite-001

tests:
  - name: "Uses correct curl format"
    assert:
      - type: regex
        value: '^curl -H "Authorization: Bearer \$API_KEY" "https://api\.github\.com/orgs/microsoft/repos\?=9&sort=stars&direction=desc"$'

  - name: "Uses Authorization Header"
    assert:
      - type:  regex
        value: 'Authorization: Bearer \$API_KEY'

  - name: "Correct GitHub API endpoint"
    assert:
      - type:  regex
        value: 'https://api\.github\.com/orgs/microsoft/repos'

  - name: "Limits to 9 repositories"
    assert:
      - type:  regex
        value: 'per_page=9'

  - name: "Sorts by stars"
    assert:
      - type:  regex
        value: 'sort=stars'

  - name: "Sorts in descending order"
    assert:
      - type:  regex
        value: 'direction=desc'

  - name: "Follows correct curl command structure"
    assert:
      - type: llm-rubric
         criteria:|
                  The response should be a complete, syntactically correct curl command in this exact structure:
                  curl -H "Authorization: Bearer $API_KEY" "https://api.github.com/orgs/microsoft/repos?per_page=9&sort=stars&direction=desc"
                  It should not omit any parameters, misplace quotation marks, or use incorrect header formatting.
